spring:

  datasource:    url: jdbc:h2:tcp://localhost/~/jpashop;MVCC=TRUE
    username : sa 
    password: 
    driver-class-name: org.h2.Driver
  jpa:    hibernate:      ddl-auto: create # reset when restrat
    properties:
     hibernate:
      show_sql : true
      format_sql : true 
  thymeleaf:    prefix: classpath:/templates/
    suffix: .html  devtools: 
    livereload: 
      enabled: 
        true # livereload 사용시 활성화 
    restart:         enabled: true
 

logging:  level:    org.hibernate.sql: info
    